# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WifiManager' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 pod 'AFNetworking', '~> 3.1.0'
 pod 'MJExtension', '~> 3.0.13'
 pod 'MJRefresh', '~> 3.1.12'
 pod 'SDWebImage', '~> 3.8.1'
 pod 'SVProgressHUD', '~> 2.0.3'
 pod 'Masonry', '~> 1.0.1'
 pod 'PNChart', '~> 0.8.9'
 pod ‘FMDB’

  # Pods for WifiManager

  target 'WifiManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WifiManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
